import type { NextPage } from 'next'
import Head from 'next/head'

import { Flex, useBreakpointValue } from '@chakra-ui/react'
import { SignInForm } from '../components/Forms/SignInForm'
import { Sidebanner } from '../components/Login/Sidebanner'
import { Logo } from '../components/Logo'

const Home: NextPage = () => {
  const isWideResolution = useBreakpointValue({
    base: false,
    lg: true,
  })

  return (
    <>
      <Head>
        <title>din.go</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Flex as={'main'} w={'100vw'} h={'100vh'} minW={'20rem'} gap='10'>
        {isWideResolution ? (
          <Sidebanner />
        ) : (
          <Logo
            display='flex'
            position='absolute'
            left='33.33%'
            top='16.66%'
            fontSize='5xl'
            fontWeight='bold'
            letterSpacing='tight'
          />
        )}

        <Flex
          flex='1'
          align={'center'}
          justifyContent={'center'}
          flexDirection={{ base: 'column', lg: 'row' }}
          gap='10'
        >
          <SignInForm />
        </Flex>
      </Flex>
    </>
  )
}

export default Home
